apiVersion: v1
kind: Pod
metadata:
  name: config-provider
spec:
  containers:
  - name: config-container
    image: busybox
    command: ["cat", "/etc/config/app-config.json"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: app-config