apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", create]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]