apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: people-tech
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K...
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400  # Un día
  usages:
  - client auth