apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-pod
  namespace: stress-demo
spec:
  containers:
  - name: cpu-stress
    image: polinux/stress
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "2"
        memory: "1Gi"
    command: ["stress"]
    args:
      - "--cpu"
      - "1"
      - "--timeout"
      - "180s"  # 3 minutos
