---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
  - secretName: envs-test-secrets
    type: Opaque
    data:
    - objectName: secret-database
      key: SECRET_DATABASE
    - objectName: parameter-config
      key: PARAMETER_CONFIG
  parameters:
    objects: |
      - objectName: "PeopleTechDataBaseSecret"
        objectType: "secretsmanager"
        objectAlias: secret-database
      - objectName: "/peopletech/config"
        objectType: "ssmparameter"
        objectAlias: parameter-config