apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Tamaño del volumen
  storageClassName: ebs-sc  # Nombre del StorageClass