apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: joca95/peopletech-tetris:v1
        ports:
        - containerPort: 3000