apiVersion: v1
kind: Service
metadata:
  name: tetris-service-nodeport
  namespace: default
spec:
  selector:
    app: tetris
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30036
  type: NodePort