apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <tu_usuario>/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          value: postgres
        - name: PGDATABASE
          value: products
        - name: PGHOST
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
spec:
  # type: NodePort
  ports:
  - port: 5000
    # targetPort: 5000
    # nodePort: 30001
  selector:
    app: backend