---
apiVersion: v1
kind: Namespace
metadata:
  name: app-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app-b
  name: deployment-app-b
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-b
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-b
    spec:
      containers:
      - image: joca95/peopletech-secrets:app-b
        imagePullPolicy: Always
        name: app-b
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: app-b
  name: service-app-b
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-b
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: app-b
  name: ingress-app-b
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: shared-alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /app-b
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /app-b
          pathType: Prefix
          backend:
            service:
              name: service-app-b
              port:
                number: 80