apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  namespace: default
spec:
  containers:
    - name: stress-cpu
      image: busybox
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
      command:
        - /bin/sh
        - -c
        - |
          echo "Starting CPU stress test";
          while true; do
            dd if=/dev/zero of=/dev/null &
          done
