apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: stress-demo
spec:
  limits:
    - max:
        memory: "2Gi"
        cpu: "1"
      min:
        memory: "100Mi"
        cpu: "100m"
      default:
        memory: "512Mi"
        cpu: "500m"
      defaultRequest:
        memory: "256Mi"
        cpu: "250m"
      type: Container