apiVersion: v1
kind: Pod
metadata:
  name: frontend-oversized
  namespace: frontend
spec:
  containers:
    - name: app
      image: nginx
      resources:
        requests:
          cpu: "2"
          memory: "2Gi"
        limits:
          cpu: "3"
          memory: "3Gi"