apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: stress-demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.memory: "2Gi"
    pods: "2"