apiVersion: v1
kind: PersistentVolume
metadata:
    name: sc-pv
spec:
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteMany
    storageClassName: manual-sc
    hostPath:
        path: /mnt/data/sc-pv